### PR TITLE
fix: #6 and other refactors

### PR DESCRIPTION
**Pull request by f3fora**
- in try-except: print replaced by logger.error
- status register, print replaced by return IntFlag
- set_frequency, args: freq, ftf (fine tuning was never performed)
- add wait function, to wait for operation complete

@alexrkaufman Can you please give a check at `set_frequency` function?

### CODE REVIEW

**Comment by alexrkaufman** [comment]
I am a fan of the [atomic commits](https://www.aleksandrhovhannisyan.com/blog/atomic-git-commits/) approach (not that I have always adhered to it). If possible I think this should be split into 3 commits. This will aid in debugging later if issues arise. Let me know if you want to divide and conquer splitting these commits up and which ones youd like me to take (I dont mind taking all 3 if that would be preferable to you, dont want to step on your toes because I think what youre doing is great). 

- [x] prints updated to logger, fixing #6 and introduction of IntFlag for statuses
- [ ] ~Update set_frequency to include fine tune frequency~
    - Moved into it's own PR #9 
- [ ] ~Adding wait function.~
    - ~Let's set `self.sleep_time` instead of `self.default_sleep_time`~
    - Moved to its own PR #8 

Currently looking into the changes to the set_frequency function. Will follow up about that in a separate comment. 

something like https://github.com/alexrkaufman/pytla/tree/example-atomic-commits maybe? would still need to align on the right approach for set_frequency but maybe we split that into it's own issue/PR?

**Comment by alexrkaufman** [comment]
re: `set_frequency` function changes

I like the goal of consolidating setting frequency into a single function. 

From what I recall, and forgive me if I am incorrect because it has been a hot minute since I had access to an ITLA, the fine tune frequency register does not reset to zero when you set the frequency registers. This could cause confusion for a user where someone sets the frequency but finds that it the frequency is offset without a clear reason because the fine tune frequency was set previously. This is why the old `set_frequency` function reset the fine tune frequency to zero each time it was called. 

Maybe something like this would work? The problem I see here is that it does provide for an option that leaves the fine tune frequency alone. 

```python
def set_frequency(self, freq, ftf=0):

... the rest of the function ...

    try:
        self.set_fine_tuning(ftf)
    except CPException:
        self.wait()
    except ExecutionError:
        self.nop()
```

**Comment by alexrkaufman** [comment]
Last comment, saw some changes to the comments in the pure photonics laser module. The following comment was removed. 

```
There is an issue in setting the first channel frequency for
the pure photonics laser as compared to the ITLA 1.3 standard.

If we set the FCF3 register it will clear the FCF2 register.
```

Is this issue no longer present in the Pure Photonics ITLA? If so, we may be able to remove the overridden `set_fcf` function altogether. Otherwise I would be happy to have this comment changed somehow, but would prefer to have some mention of the reason for the override.

**Comment by f3fora** [comment]
Pure Photonics ITLA are ITLA12, so no fcf3 register!

**Comment by f3fora** [comment]
> something like https://github.com/alexrkaufman/pytla/tree/example-atomic-commits maybe? 

thanks. that looks really good!

> would still need to align on the right approach for set_frequency but maybe we split that into it's own issue/PR?

Yes, we can certainly split the set_frequency function into its own issue/PR. It might indeed be misleading as it currently stands. Ultimately, one builds their own set_frequency in the way they find most appropriate to their purposes.

**Comment by alexrkaufman** [comment]
> Pure Photonics ITLA are ITLA12, so no fcf3 register!

Ah! That would make sense then. 
~I'll open a PR for that as well. I think as it stands the `pplaser` module inherits from `ITLA13`.~
I was just very wrong. My bad.

**Comment by f3fora** [comment]
That was already right:

https://github.com/alexrkaufman/pytla/blob/13517c7b9fb84d5fbae48cd55df3a318fa6b9d3b/itla/pplaser.py#L6C1-L6C23

**Comment by alexrkaufman** [comment]
closed by 4719ac6b9d802974d106c36bc0545b9993c10cb8

**Pull request closed without merging**
