### PR TITLE
fix some problem we faced

### PR DESCRIPTION
**Pull request by cyangy**
Hello @alexrkaufman and @NathanKuehl, Many thanks for you guys' great work , based on our recent work, we made a few changes to the code to make it work for our application. Hope this works for others.

### CODE REVIEW

**Comment by alexrkaufman** [comment]
Hi @cyangy! Thank you for using our library and submitting fixes for issues you encountered. We are very happy to know people have found our efforts helpful. 

Commits 9a47570 and d288330 are good to go and I will be happy to merge them in soon. I think commit d9f0299 touches on a larger problem which I have opened an issue for [here](https://github.com/alexrkaufman/pytla/issues/2). To determine if the issue I created actually applies to the error you encountered though I have a couple of questions: 

1. Are the NeoPhotonics and SUMITOMO ELECTRIC DEVICE INNOVATIONS devices based on the OIF-ITLA-MSA-1.3 standard? 

It is possible that these manufacturers have devices made for MSA-1.3 but their firmware only supports <=MSA-1.2.
In these cases registers 0x6[3-B] do not cause `Register Not Implemented` errors, although they should. We have encountered this with PurePhotonics lasers utilizing microITLA form factor devices.

2. Did the errors you encountered in `get_channel` and `get_frequency` occur when the register functions `_channelh` and `_fcf3` occurred? 

If this is the case it is likely that the diagnosis above is correct. I have opened an issue here [](https://github.com/alexrkaufman/pytla/issues/2) discussing possible approaches to solving this. 

3. If the error did not occur due to registers 0x6[3-B] then the issue i created is not applicable. Could you please post a stack trace of the error you are encountering?

**Comment by cyangy** [comment]
Hi, @alexrkaufman  the answer  as below:
1. Yes, the datasheet of the device mentioned it complies with **MSA-1.2**
2. The errors I encountered in `get_channel()` and `get_frequency()` occur when the register functions `_channelh()` and `_fcf3` occurred
3. if I run code below:
    ```from itla import ITLA
      s = ITLA('COM4',9600)
      s.connect()
      s.get_channel()
      s.nop()
    ```
get these output:
   ```response:65650000
    status: 1
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\cyangy\Python\lib\site-packages\itla\itla.py", line 738, in get_channel 
        response = self._channelh() + self._channel()
      File "C:\Users\cyangy\Python\lib\site-packages\itla\itla.py", line 91, in reg_fun      
        return self.get_response(register)
      File "C:\Users\cyangy\Python\lib\site-packages\itla\itla.py", line 874, in get_response
        raise self._response_status[status]
    itla.itla_errors.ExecutionError: Command returned execution error.
    >>> s.nop()
    response: 44000011
    status: 0
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\cyangy\Python\lib\site-packages\itla\itla.py", line 189, in nop
        raise self._nop_errors[error_field]
    itla.itla_errors.RNIError: RNI: Register not implemented.
```
so, instead you mentioned **Possible Solution 1** [here](https://github.com/alexrkaufman/pytla/issues/2), To avoid make this lib too complicated, I'd suggest deal  it with this way:  **Once `ExecutionError` occurs, we check _NOP_ , if  `Register Not Implemented` , will just ignore `ExecutionError ` and still return [0x00,0x00]**

**Comment by alexrkaufman** [comment]
I think part of my hesitation about commit d9f0299 is that I wouldn't feel comfortable guaranteeing this workaround for incompatibilities between the 1.2 and 1.3 specs. In particular since I initially built this library for our own research purposes it is important to me that things fail explicitly and loudly if communication with the laser is not occurring exactly as one would expect. The situation where I worry this would occur is one in which someone attempts to set some variable only to have an `RNIError` occur with no knowledge of the researcher thereby undermining or invalidating purported results. 

I have included commits 9a47570 and d288330 in the main branch and in the v0.0.3.1 release currently up on PyPI. 

**[Possible Solution 1](https://github.com/alexrkaufman/pytla/issues/2)** is not the ideal case. I believe **Possible Solution 3** is the best case which will require implementing **1** in the interim. I have included a 1.2 compatible class in the develop branch. As soon as I or someone else figures out how to make these selectable upon initialization of an ITLA object I will make it so that the interface is identical.

I believe there is a way to make this an option upon initialization without having to implement a bunch of if else statements throughout each class. 

All functions in the `ITLA12` class are identical except that they avoid the registers that did not exist prior to 1.3, 

### For now: 

```python3
import itla

# I have a laser that requires 1.2 compatibility
laser = itla.ITLA12('/dev/ttyUSB0', 9600)
laser.connect()
```

### Future desired behavior

```python3
import itla

# i have a laser that requires 1.2 compatibiltiy
laser = itla.ITLA('/dev/ttyUSB0', 9600, version=1.2)
laser.connect()
```

**Comment by alexrkaufman** [comment]
On pytla/develop aa8990d implements the future desired behavior. Figured it would be best to get this done sooner than later. I will merge this into the main and put up on pypi as soon as I can test it with actual lasers. 

Let me know if adding the option `version='1.2'` to your class initialization fixes the issues you have been running into. I will test it with our own 1.3 and 1.2 based lasers to verify but second hand confirmation is always appreciated if possible.

**Pull request closed without merging**
